version: "2"

run:
  timeout: 3m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosec
    - revive
    - gocyclo
    - misspell

  settings:
    gocyclo:
      min-complexity: 15
    errcheck:
      check-type-assertions: true
